#+title: Config
#+property: header_args :tangle config.el

* Table of Contents :toc:
- [[#doom-default-stuff][Doom Default Stuff]]
  - [[#doom-mode-line][Doom Mode Line]]
- [[#deleting-files][Deleting files]]
- [[#magit-diff-width][Magit diff width]]
- [[#magit-split][Magit split]]
- [[#whitespace-mode][Whitespace mode]]
  - [[#trim-lines-with-only-spaces-from-a-file][Trim lines with only spaces from a file]]
- [[#time][Time]]
- [[#comments][Comments]]
- [[#tree-view][Tree view]]
- [[#multiple-cursors][Multiple Cursors]]
  - [[#highlight-select][Highlight select]]
  - [[#cursor-on-next-line][Cursor on next line]]
- [[#movement][Movement]]
  - [[#moving-code][Moving code]]
- [[#character-manipulation][Character manipulation]]
  - [[#transpose-two-characters][Transpose two characters]]
- [[#window-numbering][Window numbering]]
- [[#searching][Searching]]
- [[#workspaces][Workspaces]]
  - [[#dont-open-one-when-switching-projects][Don't open one when switching projects]]
- [[#projectile][Projectile]]
  - [[#path][Path]]
  - [[#search-all-projects][Search all projects]]
- [[#dired][Dired]]
- [[#font][Font]]
- [[#file-finding][File Finding]]
- [[#sharing-or-solo-mode][Sharing or Solo mode]]
- [[#org-mode][Org Mode]]
  - [[#org-files-directory][Org Files Directory]]
  - [[#capture-templates][Capture Templates]]
- [[#ruby][Ruby]]
  - [[#compilation][Compilation]]

* Doom Default Stuff
$DOOMDIR/config.el -*- lexical-binding: t; -*-

Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!


Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src elisp :tangle yes
(setq user-full-name "Casey Allred"
      user-mail-address "sbditto85@gmail.com")
#+end_src

Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.
- `doom-unicode-font' -- for unicode glyphs
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they
accept. For example:

setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))

If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src elisp :tangle yes
(setq doom-theme 'modus-operandi)
#+end_src
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src elisp :tangle yes
(setq display-line-numbers-type 'relative)
#+end_src
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src elisp :tangle yes
(setq org-directory "~/org/")
#+end_src
Whenever you reconfigure a package, make sure to wrap your config in an
`after!' block, otherwise Doom's defaults may override your settings. E.g.

(after! PACKAGE
(setq x y))

The exceptions to this rule:

- Setting file/directory variables (like `org-directory')
- Setting variables which explicitly tell you to set them before their
  package is loaded (see 'C-h v VARIABLE' to look up their documentation).
- Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
etc).

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

** Doom Mode Line
Have the mode line truncate everything except the file

#+begin_src elisp :tangle yes

(setq doom-modeline-buffer-file-name-style 'truncate-with-project)

#+end_src

* Deleting files

Rather than sending to a recycling bin, just delete the files. I usually have git as a way of retrieving lost data

#+begin_src elisp :tangle yes
(setq delete-by-moving-to-trash nil)
(setq magit-delete-by-moving-to-trash nil)
#+end_src

* Magit diff width

Attempting to have the diff show the full width and not truncate the file names ... we shall see
#+begin_src elisp :tangle yes
(setq magit-diff-extra-stat-arguments 'magit-diff-use-window-width-as-stat-width)
#+end_src

* Magit split

#+begin_src elisp :tangle yes
(setq split-width-threshold 0)
(setq split-height-threshold 0)
;; (set-popup-rule! "magit" :slot -1 :vslot 1 :side 'right :size 0.5 :select t)
#+end_src

* Whitespace mode

#+begin_src elisp :tangle yes
(global-whitespace-mode +1)
(setq whitespace-style '(face indentation trailing))
#+end_src

** Trim lines with only spaces from a file

#+begin_src elisp :tangle yes
(defun custom/remove-space-lines ()
  (interactive)
  (evil-ex "%s/^ +$//")
  )
#+end_src

* Time
#+begin_src elisp :tangle yes
(defun custom/append-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string "%a %b %-d %Y")))

(map! :leader :desc "Insert current time" :n "d" #'custom/append-date-time)

(defun custom/insert-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string "%a %b %-d %Y")))
#+end_src

#+RESULTS:
: custom/insert-date-time

* Comments
#+begin_src elisp :tangle yes
(defun custom/author ()
  (let ((env-author (getenv "AUTHOR")))
    (if env-author
        env-author
      "custom")
    )
  )
(defun custom/comment-attribution ()
  (interactive)
  (evil-append 0)
  (insert " - " (custom/author) ", ")
  (custom/insert-date-time)
  )

(map! :leader :desc "Attribute comment" :n "c a" #'custom/comment-attribution)
#+end_src

#+RESULTS:
: custom/comment-attribution

* Tree view
#+begin_src elisp :tangle yes
;; SPC o p to toggle treemacs open and closed
(map! :leader :desc "Toogle select treemacs" :n "w SPC" #'treemacs-select-window)
#+end_src

* Multiple Cursors

** Highlight select
I want to be able to quickly highlight only a select few matches and "g z d" is just too time consuming
#+begin_src elisp :tangle yes
(map! :desc "Multiple Cursors Next Highlight" :n "M-I" #'evil-mc-make-and-goto-next-match)
(map! :desc "Multiple Cursors Next Highlight" :i "M-I" #'evil-mc-make-and-goto-next-match)
#+end_src

** Cursor on next line
I want to be able to quickly add cursors below my current one if the changes lines up perfectly
#+begin_src elisp :tangle yes
(map! :desc "Multiple Cursors Next Highlight" :n "M-i" #'evil-mc-make-cursor-move-next-line)
(map! :desc "Multiple Cursors Next Highlight" :i "M-i" #'evil-mc-make-cursor-move-next-line)
#+end_src

* Movement

#+begin_src elisp :tangle yes
(map! :desc "Down (insert mode)" :i "C-j" #'evil-next-line)
(map! :desc "Up (insert mode)" :i "C-k" #'evil-previous-line)
#+end_src

** Moving code

#+begin_src elisp :tangle yes
(global-move-dup-mode)

(map! :desc "Move line(s) up" :n "J" #'move-dup-move-lines-up)
(map! :desc "Move line(s) down" :n "K" #'move-dup-move-lines-down)

(map! :desc "Move line(s) up" :i "M-j" #'move-dup-move-lines-up)
(map! :desc "Move line(s) down" : "M-k" #'move-dup-move-lines-down)

;; (map! :desc "Duplicate line(s) up" :nvi "J" #'move-dup-duplicate-up)
;; (map! :desc "Duplicate line(s) down" :nvi "K" #'move-dup-duplicate-down)
#+end_src

* Character manipulation

** Transpose two characters

#+begin_src elisp :tangle yes
(map! :desc "Transpose/swap characters" :n "C-t" #'transpose-chars)
(map! :desc "Transpose/swap characters" :i "C-t" #'transpose-chars)
#+end_src

* Window numbering

#+begin_src elisp :tangle yes
(window-numbering-mode 1)
#+end_src

* Searching

Search with swiper in buffer
#+begin_src elisp :tangle yes
(map! :desc "Search with Swiper" :n "C-s" #'+default/search-buffer)
(map! :desc "Search with Swiper" :i "C-s" #'+default/search-buffer)
#+end_src

* Workspaces

** Don't open one when switching projects

#+begin_src elisp :tangle yes
;; (setq +workspaces-on-switch-project-behavior nil)
#+end_src

* Projectile
** Path

#+begin_src elisp :tangle yes
(defun custom/projects-path ()
  (getenv "PROJECTS_PATH")
  )

(defun custom/set-projectile-project-path ()
  (interactive)
  (let ((projects-path (custom/projects-path))
        )
    (when projects-path
      (setq projectile-project-search-path (split-string projects-path))
      )
    )
  )

(custom/set-projectile-project-path)
#+end_src

** Search all projects

#+begin_src elisp :tangle yes
(defun custom/search-projects ()
  (interactive)
  (let ((default-directory (nth 0 (split-string (custom/projects-path))))
        )
    (call-interactively
     (cond ((modulep! :completion ivy)     #'+ivy/project-search-from-cwd)
           ((modulep! :completion helm)    #'+helm/project-search-from-cwd)
           ((modulep! :completion vertico) #'+vertico/project-search-from-cwd)
           (#'rgrep))))
  )

(map! :leader :desc "Search Projects" :n "s P" #'custom/search-projects)
#+end_src

* Dired

#+begin_src elisp :tangle yes
(evil-define-key 'normal dired-mode-map
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-find-file
  )
#+end_src

* Font

#+begin_src elisp :tangle yes
(map! :leader
      (:prefix-map ("e" . "editor")
       :desc "Decrease font size"  "d"   #'doom/decrease-font-size
       :desc "Increase font size"  "i"   #'doom/increase-font-size
       :desc "Reset font size"     "r"   #'doom/reset-font-size
       ))
#+end_src

* File Finding

#+begin_src elisp :tangle yes
(map! :leader :desc "Find file at point" :n "f f" #'ffap)
#+end_src

* Sharing or Solo mode

When sharing with others the font size should be larger so its easier for them to read. When I'm solo I don't mind having the font be a bit smaller
#+begin_src elisp :tangle yes
(defun custom/set-sharing ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 185)

  ;; Setup magit to hide confusing data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header))

  ;; Set line numbering to be "normal"
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

(defun custom/set-solo ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 150)

  ;; Setup magit status to have more data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header))

  ;; Set line numbering to be relative
  ;; (setq display-line-numbers-type 'relative)
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

(custom/set-solo)
#+end_src

* Org Mode

** Org Files Directory

#+begin_src elisp :tangle yes

(defun custom/org-files-directory ()
  (or
   (getenv "ORG_FILES_DIRECTORY")
   "~/org/"
   )
  )

(setq org-directory (custom/org-files-directory))

#+end_src

** Capture Templates

#+begin_src elisp :tangle yes
(after! org
  (setq org-capture-templates
    `(("t" "Tasks / Projects")
      ("tt" "Task" entry (file+olp "tasks.org" "Inbox")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ("tc" "Task" entry (file+olp "tasks.org" "Current Work Item")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ("tp" "Task" entry (file+olp "tasks.org" "Personal")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ;; ("j" "Journal Entries")
      ;; ("jj" "Journal" entry
      ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
      ;;      ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
      ;;      :clock-in :clock-resume
      ;;      :empty-lines 1)
      ;; ("jm" "Meeting" entry
      ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
      ;;      :clock-in :clock-resume
      ;;      :empty-lines 1)

      ;; ("w" "Workflows")
      ;; ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

      ;; ("m" "Metrics Capture")
      ;; ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
      ;;  "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)
      )
    )
  )

  ;; (define-key global-map (kbd "C-c j")
  ;;   (lambda () (interactive) (org-capture nil "jj")))
  (map! :leader :desc "Task Inbox" :n "n t" (lambda () (interactive) (org-capture nil "tt")))
  (map! :leader :desc "Current Work Item Task" :n "n c" (lambda () (interactive) (org-capture nil "tc")))
  (map! :leader :desc "Personal Task" :n "n p" (lambda () (interactive) (org-capture nil "tp")))

#+end_src

* Ruby

#+begin_src elisp :tangle yes
(add-hook 'ruby-mode-hook 'evil-ruby-text-objects-mode)
#+end_src

** Compilation

#+begin_src elisp :tangle no
(add-hook 'ruby-mode-hook
          (lambda ()
            (set (make-local-variable 'compile-command)
                 (concat "ruby " buffer-file-name))
            (set (make-local-variable 'compilation-read-command) nil)
            )
          )
#+end_src

*** Aaron's config

#+begin_src elisp :tangle no

(use-feature ruby-mode
             :config
             (defun aj-eval-ruby (detail)
               "Eval the current ruby file."
               (interactive "P")
               (when (buffer-file-name)
                 (save-buffer)

                 (let* ((default-directory (aj-project-root))
                        (env "RUBYOPT='-W:no-deprecated -W:no-experimental'")
                        (env (if detail
                                 (concat "TEST_BENCH_DETAIL=on " env)
                               env))
                        (relative-file-name (file-relative-name buffer-file-name default-directory))
                        (command (concat env " ruby " (shell-quote-argument relative-file-name)))
                        (compilation-scroll-output 'first-error))
                   (compilation-start command 'ruby-compilation-mode))))

             (leader-key-set-for-major-mode 'ruby-mode
                                            "e" #'aj-eval-ruby)

             (after evil
                    (evil-declare-abort-repeat #'aj-eval-ruby))

             (add-hook 'compilation-shell-minor-mode-hook #'read-only-mode)
             (add-hook 'compilation-shell-minor-mode-hook #'evil-motion-state)

             (define-derived-mode ruby-compilation-mode compilation-mode "Ruby Compilation"
               (setq-local compilation-error-regexp-alist '(ruby-testbench))))

(use-feature compile
             :config
             (cl-pushnew '(ruby-testbench "[[:space:]]+\\([0-9A-za-z@_./:-]+\\.rb\\):\\([0-9]+\\):in" 1 2 nil 2 1)
                         compilation-error-regexp-alist-alist)
             (add-to-list 'compilation-error-regexp-alist 'ruby-testbench))

#+end_src
