#+title: Config
#+property: header_args :tangle config.el

* Table of Contents :toc:
- [[#doom-default-stuff][Doom Default Stuff]]
- [[#display][Display]]
- [[#deleting-files][Deleting files]]
- [[#magit-diff-width][Magit diff width]]
- [[#magit-split][Magit split]]
- [[#whitespace-mode][Whitespace mode]]
  - [[#trim-lines-with-only-spaces-from-a-file][Trim lines with only spaces from a file]]
- [[#time][Time]]
- [[#comments][Comments]]
- [[#tree-view][Tree view]]
- [[#multiple-cursors][Multiple Cursors]]
  - [[#highlight-select][Highlight select]]
  - [[#cursor-on-next-line][Cursor on next line]]
- [[#movement][Movement]]
- [[#window-numbering][Window numbering]]
- [[#searching][Searching]]
- [[#workspaces][Workspaces]]
  - [[#dont-open-one-when-switching-projects][Don't open one when switching projects]]
- [[#projectile][Projectile]]
  - [[#doom-mode-line][Doom Mode Line]]
  - [[#path][Path]]
  - [[#search-all-projects][Search all projects]]
- [[#dired][Dired]]
- [[#font][Font]]
- [[#file-finding][File Finding]]
  - [[#switch-buffer-list][Switch Buffer List]]
- [[#sharing-or-solo-mode][Sharing or Solo mode]]
- [[#org-mode][Org Mode]]
  - [[#org-files-directory][Org Files Directory]]
  - [[#org-mobile][Org Mobile]]
  - [[#capture-templates][Capture Templates]]
- [[#ruby][Ruby]]
  - [[#compilation][Compilation]]
- [[#disabled-casing][DISABLED Casing]]
- [[#running-tests][Running tests]]
- [[#aarons-config][Aaron's config]]
  - [[#ruby-mode][Ruby mode]]
  - [[#people-tag][People tag]]
- [[#experimental-header-line-format][Experimental header-line-format]]
- [[#experimental-task-manager][Experimental Task Manager]]
- [[#experimental-remove-mode-line][Experimental remove mode line]]
- [[#evil-escape][Evil escape]]

* Doom Default Stuff
$DOOMDIR/config.el -*- lexical-binding: t; -*-

Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!


Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src elisp :tangle yes
(setq user-full-name "Casey Allred"
      user-mail-address "sbditto85@gmail.com")
#+end_src

Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.
- `doom-unicode-font' -- for unicode glyphs
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they
accept. For example:

setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))

If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src elisp :tangle yes
(setq doom-theme 'modus-operandi)
#+end_src
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src elisp :tangle yes
(setq display-line-numbers-type 'relative)
#+end_src
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!

#+begin_src elisp :tangle yes
(setq org-directory "~/org/")
#+end_src
Whenever you reconfigure a package, make sure to wrap your config in an
`after!' block, otherwise Doom's defaults may override your settings. E.g.

(after! PACKAGE
(setq x y))

The exceptions to this rule:

- Setting file/directory variables (like `org-directory')
- Setting variables which explicitly tell you to set them before their
  package is loaded (see 'C-h v VARIABLE' to look up their documentation).
- Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
etc).

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

* Display

#+begin_src elisp :tangle yes
(setq default-frame-alist
  (append
    (list
      '(inhibit-double-buffering . t)
      )
      default-frame-alist
    )
  )
#+end_src

Aaron send a block of example code to show demonstrate setting `inhibit-double-buffering` to prevent screen fragments
#+begin_src elisp :tangle no
(setq default-frame-alist
      (append
       (list
        `(font . ,(concat aj-fixed-font "-" (number-to-string aj-fixed-font-default-size)))
        '(min-height . 1) '(height . 45)
        '(min-width . 1) '(width . 81)
        '(vertical-scroll-bars . nil)
        '(internal-border-width . 0)
        '(left-fringe . 16)
        '(right-fringe . 16)
        '(tool-bar-lines . 0)
        '(menu-bar-lines . 0)
        '(undecorated-round . t)
        '(inhibit-double-buffering . t)
        ;; ns-auto-titlebar will take care of this for any other frames and when
        ;; switching to a dark theme, but this is set here to avoid loading
        ;; ns-auto-titlebar on init
        '(ns-transparent-titlebar . t)
        '(ns-appearance . light))
       default-frame-alist))
#+end_src

* Deleting files

Rather than sending to a recycling bin, just delete the files. I usually have git as a way of retrieving lost data

#+begin_src elisp :tangle yes
(setq delete-by-moving-to-trash nil)
(setq magit-delete-by-moving-to-trash nil)
#+end_src

* Magit diff width

Attempting to have the diff show the full width and not truncate the file names ... we shall see
#+begin_src elisp :tangle yes
(setq magit-diff-extra-stat-arguments 'magit-diff-use-window-width-as-stat-width)
#+end_src

* Magit split

#+begin_src elisp :tangle yes
(setq split-width-threshold 0)
(setq split-height-threshold 0)
;; (set-popup-rule! "magit" :slot -1 :vslot 1 :side 'right :size 0.5 :select t)
#+end_src

* Whitespace mode

#+begin_src elisp :tangle yes
(global-whitespace-mode +1)
(setq whitespace-style '(face indentation trailing))
#+end_src

** Trim lines with only spaces from a file

#+begin_src elisp :tangle yes
(defun custom/remove-space-lines ()
  (interactive)
  (evil-ex "%s/^ +$//")
  )
#+end_src

* Time
#+begin_src elisp :tangle yes
(defun custom/time-format ()
  (let ((env-time-day-leading-zero (getenv "TIME_DAY_LEADING_ZERO")))
    (if (string= env-time-day-leading-zero "off")
        "%a %b %d %Y"
      "%a %b %-d %Y")
    )
  )

(defun custom/append-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string (custom/time-format))))

(map! :leader :desc "Insert current time" :n "d" #'custom/append-date-time)

(defun custom/insert-date-time ()
  (interactive)
  (evil-append 0)
  (insert (format-time-string (custom/time-format))))
#+end_src

#+RESULTS:
: custom/insert-date-time

* Comments
#+begin_src elisp :tangle yes
(defun custom/author ()
  (let ((env-author (getenv "AUTHOR")))
    (if env-author
        env-author
      "custom")
    )
  )
(defun custom/comment-attribution ()
  (interactive)
  (save-excursion
    (evil-append 0)
    (insert " - " (custom/author) ", ")
    (custom/insert-date-time)
    )
  )

(map! :leader :desc "Attribute comment" :n "c a" #'custom/comment-attribution)
#+end_src

#+RESULTS:
: custom/comment-attribution

* Tree view
#+begin_src elisp :tangle yes
;; SPC o p to toggle treemacs open and closed
(map! :leader :desc "Toogle select treemacs" :n "w SPC" #'treemacs-select-window)

(setq treemacs-wrap-around nil)

(after! treemacs
  (treemacs-follow-mode t)
  )
#+end_src

* Multiple Cursors

** Highlight select
I want to be able to quickly highlight only a select few matches and "g z d" is just too time consuming
#+begin_src elisp :tangle yes
(map! :desc "Multiple Cursors Next Highlight" :n "M-I" #'evil-mc-make-and-goto-next-match)
(map! :desc "Multiple Cursors Next Highlight" :i "M-I" #'evil-mc-make-and-goto-next-match)
#+end_src

** Cursor on next line
I want to be able to quickly add cursors below my current one if the changes lines up perfectly
#+begin_src elisp :tangle yes
(map! :desc "Multiple Cursors Next Highlight" :n "M-i" #'evil-mc-make-cursor-move-next-line)
(map! :desc "Multiple Cursors Next Highlight" :i "M-i" #'evil-mc-make-cursor-move-next-line)
#+end_src

* Movement

#+begin_src elisp :tangle yes
(map! :desc "Down (insert mode)" :i "C-j" #'evil-next-line)
(map! :desc "Up (insert mode)" :i "C-k" #'evil-previous-line)
#+end_src

* Window numbering

#+begin_src elisp :tangle yes
(window-numbering-mode 1)
#+end_src

* Searching

Search with swiper in buffer
#+begin_src elisp :tangle yes
(map! :desc "Search with Swiper" :n "C-s" #'+default/search-buffer)
(map! :desc "Search with Swiper" :i "C-s" #'+default/search-buffer)
#+end_src

* Workspaces

** Don't open one when switching projects

#+begin_src elisp :tangle yes
;; (setq +workspaces-on-switch-project-behavior nil)
#+end_src

* Projectile
** Doom Mode Line
Set the mode line to show the project and then truncate the rest of the path until the file

#+begin_src elisp :tangle yes

(setq doom-modeline-buffer-file-name-style 'truncate-with-project)

#+end_src

** Path

#+begin_src elisp :tangle yes
(defun custom/projects-path ()
  (getenv "PROJECTS_PATH")
  )

(defun custom/set-projectile-project-path ()
  (interactive)
  (let ((projects-path (custom/projects-path))
        )
    (when projects-path
      (setq projectile-project-search-path (split-string projects-path))
      )
    )
  )

(custom/set-projectile-project-path)
#+end_src

** Search all projects

#+begin_src elisp :tangle yes
(defun custom/search-projects ()
  (interactive)
  (let ((default-directory (nth 0 (split-string (custom/projects-path))))
        )
    (call-interactively
     (cond ((modulep! :completion ivy)     #'+ivy/project-search-from-cwd)
           ((modulep! :completion helm)    #'+helm/project-search-from-cwd)
           ((modulep! :completion vertico) #'+vertico/project-search-from-cwd)
           (#'rgrep))))
  )

(map! :leader :desc "Search Projects" :n "s P" #'custom/search-projects)
#+end_src

* Dired

#+begin_src elisp :tangle yes
(evil-define-key 'normal dired-mode-map
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-find-file
  )
#+end_src

* Font

#+begin_src elisp :tangle yes
(map! :leader
      (:prefix-map ("e" . "editor")
       :desc "Decrease font size"  "d"   #'doom/decrease-font-size
       :desc "Increase font size"  "i"   #'doom/increase-font-size
       :desc "Reset font size"     "r"   #'doom/reset-font-size
       ))
#+end_src

* File Finding

#+begin_src elisp :tangle yes
(map! :leader :desc "Find file at point" :n "f f" #'ffap)
#+end_src

** Switch Buffer List

#+begin_src elisp :tangle yes
(after! ivy-rich
  (ivy-rich-set-columns
   'ivy-switch-buffer
   '((ivy-switch-buffer-transformer (:width 0.2))
     (ivy-rich-switch-buffer-indicators (:width 4 :face error :align right))
     (ivy-rich-switch-buffer-major-mode (:width 12 :face warning))
     (ivy-rich-switch-buffer-path
      (:width
       (lambda (x)
         (ivy-rich-switch-buffer-shorten-path x (ivy-rich-minibuffer-width 0.7))
         )
       )
      )
     )
   )
  )
#+end_src

* Sharing or Solo mode

When sharing with others the font size should be larger so its easier for them to read. When I'm solo I don't mind having the font be a bit smaller
#+begin_src elisp :tangle yes
(defun custom/set-sharing ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 185)

  ;; Setup magit to hide confusing data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header))

  ;; Set line numbering to be "normal"
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

(defun custom/set-solo ()
  (interactive)

  ;; Set the font size
  (set-face-attribute 'default nil :height 150)

  ;; Setup magit status to have more data
  (setq magit-status-headers-hook
        '(magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header))

  ;; Set line numbering to be relative
  ;; (setq display-line-numbers-type 'relative)
  (setq display-line-numbers-type t)
  (global-display-line-numbers-mode -1)
  (global-display-line-numbers-mode 1)
  )

(custom/set-solo)
#+end_src

* Org Mode

** Org Files Directory

#+begin_src elisp :tangle yes

(defun custom/org-files-directory ()
  (or
   (getenv "ORG_FILES_DIRECTORY")
   "~/org/"
   )
  )

(setq org-directory (custom/org-files-directory))

#+end_src

** Org Mobile

#+begin_src elisp :tangle yes

(setq org-mobile-inbox-for-pull (concat (custom/org-files-directory) "inbox.org"))
(setq org-mobile-directory "~/Dropbox/Apps/MobileOrg")

(after! org
  (map! :leader :desc "Org Mobile Push" :n "n o" #'org-mobile-push)
  (map! :leader :desc "Org Mobile Pull" :n "n i" #'org-mobile-pull)
  )

#+end_src

** Capture Templates

#+begin_src elisp :tangle yes
(after! org
  (setq org-capture-templates
    `(("t" "Tasks / Projects")
      ("tt" "Task" entry (file+olp "tasks.org" "Inbox")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ("tc" "Task" entry (file+olp "tasks.org" "Current Work Item")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ("tp" "Task" entry (file+olp "tasks.org" "Personal")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

      ;; ("j" "Journal Entries")
      ;; ("jj" "Journal" entry
      ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
      ;;      ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
      ;;      :clock-in :clock-resume
      ;;      :empty-lines 1)
      ;; ("jm" "Meeting" entry
      ;;      (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
      ;;      :clock-in :clock-resume
      ;;      :empty-lines 1)

      ;; ("w" "Workflows")
      ;; ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
      ;;      "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

      ;; ("m" "Metrics Capture")
      ;; ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
      ;;  "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)
      )
  )

  ;; (define-key global-map (kbd "C-c j")
  ;;   (lambda () (interactive) (org-capture nil "jj")))
  (map! :leader :desc "Task Inbox" :n "n t" (lambda () (interactive) (org-capture nil "tt")))
  (map! :leader :desc "Current Work Item Task" :n "n c" (lambda () (interactive) (org-capture nil "tc")))
  (map! :leader :desc "Personal Task" :n "n p" (lambda () (interactive) (org-capture nil "tp")))
  )

#+end_src

* Ruby

#+begin_src elisp :tangle yes
(add-hook 'ruby-mode-hook 'evil-ruby-text-objects-mode)

(setq ruby-block-indent nil
      ruby-method-call-indent nil
      ruby-method-params-indent nil
      ruby-after-operator-indent nil
      ruby-bracketed-args-indent nil)
#+end_src

** Compilation

#+begin_src elisp :tangle no
(add-hook 'ruby-mode-hook
          (lambda ()
            (set (make-local-variable 'compile-command)
                 (concat "ruby " buffer-file-name))
            (set (make-local-variable 'compilation-read-command) nil)
            )
          )
#+end_src


* DISABLED Casing

#+begin_src elisp :tangle no

  (map! :leader :desc "Ruby Casing Cycle" :n "t t" #'string-inflection-ruby-style-cycle)

#+end_src

* Running tests

You can call ==vterm-send-string== when the current buffer is in ==vterm-mode==, which if you include a "\n" it will "hit enter" as if you were typing commands

#+begin_src elisp :tangle yes

  (defun custom/test-component-project ()
    (interactive)
    (if (equal current-prefix-arg nil)
        (custom/split-with-process "ct")
        (custom/split-with-process "s && ct")
      ))

  (defun custom/test-web-project ()
    (interactive)
    (if (equal current-prefix-arg nil)
        (custom/split-with-process "prs")
        (custom/split-with-process "s && prs")
      ))

  (defun custom/split-with-process (command)
    (let ((test-buffer (generate-new-buffer "*testing*"))
          (process-buffer (generate-new-buffer "*process*")))
      (switch-to-buffer process-buffer)
      (vterm-mode)
      (vterm-send-string command)
      (vterm-send-return)
      (split-window-right)
      (switch-to-buffer test-buffer)
      (vterm-mode)
      ))

#+end_src

* Aaron's config

** Ruby mode

For Emacs 30 to have better auto indention of ruby code blocks
#+begin_src elisp :tangle no

(setq ruby-block-indent nil
      ruby-method-call-indent nil
      ruby-method-params-indent nil
      ruby-after-operator-indent nil
      ruby-bracketed-args-indent nil)

#+end_src

#+begin_src elisp :tangle no

(use-feature ruby-mode
             :config
             (defun aj-eval-ruby (detail)
               "Eval the current ruby file."
               (interactive "P")
               (when (buffer-file-name)
                 (save-buffer)

                 (let* ((default-directory (aj-project-root))
                        (env "RUBYOPT='-W:no-deprecated -W:no-experimental'")
                        (env (if detail
                                 (concat "TEST_BENCH_DETAIL=on " env)
                               env))
                        (relative-file-name (file-relative-name buffer-file-name default-directory))
                        (command (concat env " ruby " (shell-quote-argument relative-file-name)))
                        (compilation-scroll-output 'first-error))
                   (compilation-start command 'ruby-compilation-mode))))

             (leader-key-set-for-major-mode 'ruby-mode
                                            "e" #'aj-eval-ruby)

             (after evil
                    (evil-declare-abort-repeat #'aj-eval-ruby))

             (add-hook 'compilation-shell-minor-mode-hook #'read-only-mode)
             (add-hook 'compilation-shell-minor-mode-hook #'evil-motion-state)

             (define-derived-mode ruby-compilation-mode compilation-mode "Ruby Compilation"
               (setq-local compilation-error-regexp-alist '(ruby-testbench))))

(use-feature compile
             :config
             (cl-pushnew '(ruby-testbench "[[:space:]]+\\([0-9A-za-z@_./:-]+\\.rb\\):\\([0-9]+\\):in" 1 2 nil 2 1)
                         compilation-error-regexp-alist-alist)
             (add-to-list 'compilation-error-regexp-alist 'ruby-testbench))

#+end_src

** People tag

#+begin_src elisp :tangle no

(defun aj-work-log-people-self ()
  (if (or (string= (aj-project-name) "work-logs")
          (eq major-mode 'org-journal-mode))
      "self"
    "Aaron"))

(defun aj-work-log-people-insert-self ()
  (interactive)
  (aj-work-log-people-insert (aj-work-log-people-self))
  (aj-work-log-people-sort))

(defun aj-work-log-people-sort ()
  "Sort the people names, ensuring 'self' is last if present."
  (interactive)
  (beginning-of-line)
  (when (re-search-forward "\\[people\\] \\(.*?\\)$" (line-end-position) t)
    (let* ((people (match-string 1))
           (people-list (save-match-data (split-string people ", " t " ")))
           (sorted-people-list (sort people-list 'string<)))
      (replace-match (concat "[people] " (string-join people-list ", ")))))
  (end-of-line))

(defun aj-work-log-people-insert (person)
  "Insert a person into the [people] tag."
  (interactive "sPerson: ")
  (if (looking-back "\\[people\\] ")
      (insert person)
    (insert (concat ", " person))))

(defun aj-work-log-people-backspace ()
  "Delete to the previous comma or `]` in the [people] tag."
  (interactive)
  (save-excursion
    (if (re-search-backward ", " (line-beginning-position) t)
        (progn
          (delete-region (match-beginning 0) (line-end-position)))
      (when (re-search-backward "\\[people\\] " (line-beginning-position) t)
        (delete-region (match-end 0) (line-end-position))))))

(defhydra aj-work-log-people (:foreign-keys run)
  "Insert names into [people] tag."
  ("aa" (aj-work-log-people-insert-self) "Aaron" :exit t)
  ("ad" (aj-work-log-people-insert "Annie") "Annie")
  ("an" (aj-work-log-people-insert "Antoine") "Antoine")
  ("ca" (aj-work-log-people-insert "Casey") "Casey")
  ("cb" (aj-work-log-people-insert "Chris") "Chris")
  ("cg" (aj-work-log-people-insert "Christina") "Christina")
  ("da" (aj-work-log-people-insert "David") "David")
  ("du" (aj-work-log-people-insert "Dustin") "Dustin")
  ("et" (aj-work-log-people-insert "Ethan") "Ethan")
  ("gr" (aj-work-log-people-insert "Grace") "Grace")
  ("ka" (aj-work-log-people-insert "Kacey") "Kacey")
  ("ke" (aj-work-log-people-insert "Kelly") "Kelly")
  ("ma" (aj-work-log-people-insert "Matt") "Matt")
  ("mi" (aj-work-log-people-insert "Miles") "Miles")
  ("na" (aj-work-log-people-insert "Nathan") "Nathan")
  ("ni" (aj-work-log-people-insert "Nick") "Nick")
  ("sa" (aj-work-log-people-insert "Scott A") "Scott A")
  ("sb" (aj-work-log-people-insert "Scott B") "Scott B")
  ("sh" (aj-work-log-people-insert "Shaun") "Shaun")
  ("st" (aj-work-log-people-insert "Stephen") "Stephen")
  ("wa" (aj-work-log-people-insert "Walker") "Walker")
  ("<return>" (aj-work-log-people-insert-self) "Aaron" :exit t)
  ("<backspace>" (aj-work-log-people-backspace))
  ("q" (aj-work-log-people-sort) "quit" :exit t)
  ("C-g" (aj-work-log-people-sort) "quit" :hint nil :exit t)
  ("<escape>" (aj-work-log-people-sort) "quit" :hint nil :exit t)
  ("," aj-work-log-people-insert "Other"))

(defun aj-work-log-people ()
  "Insert a [people] tag."
  (interactive)
  (insert "[people] ")
  (aj-work-log-people/body))

(define-key markdown-mode-map (kbd "C-c C-p") #'aj-work-log-people)
#+end_src

* Experimental header-line-format

Generated this with Claude using the prompt "Can you generate a header-line-format that will show the current file name, project name on the right and then the point location to the right side?" after asking it questions to learn about the ==header-line-format==

#+begin_src elisp :tangle yes
(defun my/header-line-format ()
  "Create a custom header line format with side padding, task info, and right-aligned point information."
  (let* ((file-name (or (buffer-file-name) (buffer-name)))
         (short-file-name (file-name-nondirectory file-name))
         (project-name (when (fboundp 'project-current)
                         (let ((project (project-current)))
                           (when project
                             (file-name-nondirectory
                              (directory-file-name
                               (project-root project)))))))
         (point-info (format "L%d C%d" (line-number-at-pos) (current-column)))
         (modified (if (buffer-modified-p) "*" ""))
         (side-padding "   ") ;; 3 spaces padding

         ;; Task information
         (task-info (format "[%s]"
                     (or (and (boundp 'task-manager-current-task)
                              task-manager-current-task
                              (fboundp 'task-manager-task-text)
                              (task-manager-task-text task-manager-current-task))
                         "None")))

         ;; Left content (with side padding)
         (left-content (format "%s%s%s%s"
                               side-padding
                               short-file-name
                               modified
                               (if project-name (format " [%s]" project-name) "")))

         (window-width (window-total-width))

         ;; Calculate padding for right side
         (right-content (format "%s %s" task-info point-info))
         (padding (make-string (max 1 (- window-width
                                        (length left-content)
                                        (length right-content)
                                        (length side-padding)))
                               ? )))

    (format "%s%s%s%s"
            (propertize left-content 'face 'font-lock-keyword-face)
            (propertize padding 'face 'default)
            (propertize task-info 'face 'font-lock-string-face)
            (propertize (concat " " point-info side-padding) 'face 'font-lock-comment-face))))

;; Set the header-line-format
(setq-default header-line-format '(:eval (my/header-line-format)))

;; Alternative approach with debouncing
(defvar my/header-update-timer nil)

(defun my/schedule-header-update ()
  (when my/header-update-timer
    (cancel-timer my/header-update-timer))
  (setq my/header-update-timer
        (run-with-idle-timer 0.1 nil #'force-mode-line-update)))

(add-hook 'post-command-hook 'my/schedule-header-update)

#+end_src


* Experimental Task Manager

Bindings for my vibe coded task manager

#+begin_src elisp :tangle yes

  (map! :leader :desc "Toggle Task Manager" :n "t t" #'task-manager-toggle)
  (map! :leader :desc "Add Task" :n "t a" #'task-manager-quick-add-task)

#+end_src


* Experimental remove mode line

#+begin_src elisp :tangle yes

;; Completely disable the mode line
(setq-default mode-line-format nil)

;; Add a hook to ensure mode-line stays disabled
(add-hook 'after-change-major-mode-hook
          (lambda () (setq mode-line-format nil)))

;; Disable related packages that might be bringing it back
(after! doom-modeline
  (doom-modeline-mode -1))

#+end_src

* Evil escape

#+begin_src elisp :tangle yes

(evil-escape-mode 1)

(setq-default evil-escape-key-sequence "jk")

#+end_src
